source 'https://rubygems.org'

gem 'discordrb', git: 'https://github.com/meew0/discordrb.git'
gem 'mechanize', '~>2.7.5'
gem 'giphy', '~>3.0.0'
gem 'geocoder', '~>1.4.1'
gem 'forecast_io', '~>2.0.1'
gem 'chronic'
gem 'chronic_duration', '~>0.10.6'
gem 'capybara', '~>2.11.0'
gem 'poltergeist', '~>1.12.0'
gem 'nokogiri', '~>1.6.8'
gem 'sqlite3', '~>1.3.12'
gem 'gruff', '~>0.7.0'
gem 'builder'
gem 'rmagick'
gem 'rerun'
gem 'pg'

gem 'rspec'
gem 'rspec-mocks'
gem 'webmock'
gem 'reverse-markdown'
gem 'activerecord'
gem 'htmlentities'
gem 'stock_quote'
gem 'text-table'
